<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Logout_closeModalButton</name>
   <tag></tag>
   <elementGuidId>54b2ee02-3158-48a6-a877-1a9717908e44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closeModalButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='closeModalButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c9d0b1dd-e0bc-4c77-a743-51c09b6cf445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>b690a73d-c471-4cb7-8a52-3dded2614021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>e58ba323-6c73-44ee-9ebc-25fe20260cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeModalButton</value>
      <webElementGuid>1244624b-cf4c-49d6-abcb-a368543262c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeModalButton&quot;)</value>
      <webElementGuid>b61e2d21-5b5c-4e9b-a777-a05aeb94c6ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='closeModalButton']</value>
      <webElementGuid>8767025e-60f6-47ba-99a2-fdc749ef5c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModal']/div[2]/header/button</value>
      <webElementGuid>d4e60b90-c0b6-431a-a9e5-39882babb578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>5b1266cd-8016-4ca8-933a-d6f33b01772d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'closeModalButton']</value>
      <webElementGuid>013a94be-ffe7-411c-80a4-4e6a6b715372</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
