<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Batal_showModalButton</name>
   <tag></tag>
   <elementGuidId>618f84be-9552-41c2-b532-53aa51a79bba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#showModalButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='showModalButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0fc59fe1-7717-4442-9a3a-1ab58c646a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button is-warning is-rounded fixed-button is-large</value>
      <webElementGuid>87a34c69-401d-40e5-882f-2f346dde4447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showModalButton</value>
      <webElementGuid>e07d1bda-8557-4d21-aea5-3a07887b2940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showModalButton&quot;)</value>
      <webElementGuid>2ca15ed6-c4d6-4941-b409-6f2119d21a5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='showModalButton']</value>
      <webElementGuid>9d28f3f8-c2df-480e-8d9d-8e67e5b2e9e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::button[1]</value>
      <webElementGuid>f3be8fff-6f3d-43fa-8139-ac04884bc28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/following::button[2]</value>
      <webElementGuid>d10620f9-187a-4dd2-8ecd-4cbbf3d7a456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/button</value>
      <webElementGuid>d2f454a6-ddae-4362-8b4b-936e3af26959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'showModalButton']</value>
      <webElementGuid>897ce75e-0ff2-4573-a6d7-3f2c8c5827b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
